-- SQL Command to insert all restaurants into the database
-- Execute this in your MySQL database or phpMyAdmin

INSERT INTO restaurants (name, code, address, status, created_at, updated_at) VALUES
('Abha', 'R001', 'Saudi Arabia', 'active', NOW(), NOW()),
('Abha-TNDR', 'R002', 'Saudi Arabia', 'active', NOW(), NOW()),
('Al-Qassim', 'R003', 'Saudi Arabia', 'active', NOW(), NOW()),
('Al-Sultan-T', 'R004', 'Saudi Arabia', 'active', NOW(), NOW()),
('Albadia', 'R005', 'Saudi Arabia', 'active', NOW(), NOW()),
('Ameer Fawaz', 'R006', 'Saudi Arabia', 'active', NOW(), NOW()),
('Awali', 'R007', 'Saudi Arabia', 'active', NOW(), NOW()),
('Aziziyah-Madina', 'R008', 'Saudi Arabia', 'active', NOW(), NOW()),
('Aziziyah-Riyad', 'R009', 'Saudi Arabia', 'active', NOW(), NOW()),
('Basateen', 'R010', 'Saudi Arabia', 'active', NOW(), NOW()),
('Batha Quresh', 'R011', 'Saudi Arabia', 'active', NOW(), NOW()),
('DAMMAM', 'R012', 'Saudi Arabia', 'active', NOW(), NOW()),
('Dahiat Laban', 'R013', 'Saudi Arabia', 'active', NOW(), NOW()),
('Faisaliya', 'R014', 'Saudi Arabia', 'active', NOW(), NOW()),
('Hail', 'R015', 'Saudi Arabia', 'active', NOW(), NOW()),
('Hamdaniya', 'R016', 'Saudi Arabia', 'active', NOW(), NOW()),
('Hamdaniya-TNDR', 'R017', 'Saudi Arabia', 'active', NOW(), NOW()),
('Hassan Bin Thabit', 'R018', 'Saudi Arabia', 'active', NOW(), NOW()),
('Hijra', 'R019', 'Saudi Arabia', 'active', NOW(), NOW()),
('Hira', 'R020', 'Saudi Arabia', 'active', NOW(), NOW()),
('Iceland', 'R021', 'Saudi Arabia', 'active', NOW(), NOW()),
('Imam Saud -TNDR', 'R022', 'Saudi Arabia', 'active', NOW(), NOW()),
('KHARG', 'R023', 'Saudi Arabia', 'active', NOW(), NOW()),
('KING FAHAD MED', 'R024', 'Saudi Arabia', 'active', NOW(), NOW()),
('Khaleej', 'R025', 'Saudi Arabia', 'active', NOW(), NOW()),
('Khamis Mushet', 'R026', 'Saudi Arabia', 'active', NOW(), NOW()),
('Khobar', 'R027', 'Saudi Arabia', 'active', NOW(), NOW()),
('Khulias', 'R028', 'Saudi Arabia', 'active', NOW(), NOW()),
('King Salman', 'R029', 'Saudi Arabia', 'active', NOW(), NOW()),
('Marwa', 'R030', 'Saudi Arabia', 'active', NOW(), NOW()),
('Marwa-TNDR', 'R031', 'Saudi Arabia', 'active', NOW(), NOW()),
('Mohamadiah', 'R032', 'Saudi Arabia', 'active', NOW(), NOW()),
('Nahdah', 'R033', 'Saudi Arabia', 'active', NOW(), NOW()),
('Nakheel', 'R034', 'Saudi Arabia', 'active', NOW(), NOW()),
('Nassem', 'R035', 'Saudi Arabia', 'active', NOW(), NOW()),
('Nassem-TNDR', 'R036', 'Saudi Arabia', 'active', NOW(), NOW()),
('Nozha', 'R037', 'Saudi Arabia', 'active', NOW(), NOW()),
('Obhur', 'R038', 'Saudi Arabia', 'active', NOW(), NOW()),
('Qurtuba', 'R039', 'Saudi Arabia', 'active', NOW(), NOW()),
('Rabigh', 'R040', 'Saudi Arabia', 'active', NOW(), NOW()),
('Raqi', 'R041', 'Saudi Arabia', 'active', NOW(), NOW()),
('Rawabi Plaza', 'R042', 'Saudi Arabia', 'active', NOW(), NOW()),
('Rehab', 'R043', 'Saudi Arabia', 'active', NOW(), NOW()),
('Riy-Warehouse Dep', 'R044', 'Saudi Arabia', 'active', NOW(), NOW()),
('Riyadh- Factory', 'R045', 'Saudi Arabia', 'active', NOW(), NOW()),
('Rowdah', 'R046', 'Saudi Arabia', 'active', NOW(), NOW()),
('Rowdah-TNDR', 'R047', 'Saudi Arabia', 'active', NOW(), NOW()),
('Samer', 'R048', 'Saudi Arabia', 'active', NOW(), NOW()),
('King Salman 2', 'R049', 'Saudi Arabia', 'active', NOW(), NOW()),
('Sari', 'R050', 'Saudi Arabia', 'active', NOW(), NOW()),
('Shoukiya', 'R051', 'Saudi Arabia', 'active', NOW(), NOW()),
('Shraia', 'R052', 'Saudi Arabia', 'active', NOW(), NOW()),
('Sultana -TNDR', 'R053', 'Saudi Arabia', 'active', NOW(), NOW()),
('Tahlia', 'R054', 'Saudi Arabia', 'active', NOW(), NOW()),
('Taif-Hawiyah', 'R055', 'Saudi Arabia', 'active', NOW(), NOW()),
('Taif-Shehar', 'R056', 'Saudi Arabia', 'active', NOW(), NOW()),
('Thumama', 'R057', 'Saudi Arabia', 'active', NOW(), NOW()),
('Umluj', 'R058', 'Saudi Arabia', 'active', NOW(), NOW()),
('Waziriyah', 'R059', 'Saudi Arabia', 'active', NOW(), NOW()),
('Yanbu 1', 'R060', 'Saudi Arabia', 'active', NOW(), NOW()),
('Yanbu 2', 'R061', 'Saudi Arabia', 'active', NOW(), NOW()),
('Yasmen', 'R062', 'Saudi Arabia', 'active', NOW(), NOW()),
('Zaidi (Sasco)', 'R063', 'Saudi Arabia', 'active', NOW(), NOW()),
('Jed-Warehouse Dep', 'R064', 'Saudi Arabia', 'active', NOW(), NOW()),
('Jeddah Factory', 'R065', 'Saudi Arabia', 'active', NOW(), NOW());

-- Check if data was inserted correctly
SELECT COUNT(*) as total_restaurants FROM restaurants;
SELECT name, code FROM restaurants ORDER BY code;